services:
  - type: web
    name: khushi-hr
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: ADMIN_JWT_SECRET
        generateValue: true
